CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE TABLE "Capelas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Localizacao" text NOT NULL,
        "Status" character varying(50) NOT NULL,
        CONSTRAINT "PK_Capelas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "Email" character varying(150) NOT NULL,
        "SenhaHash" text NOT NULL,
        "NivelAcesso" integer NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE TABLE "Obitos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeFalecido" character varying(150) NOT NULL,
        "DataObito" timestamp with time zone NOT NULL,
        "CausaMortis" text NOT NULL,
        "CapelaId" integer NOT NULL,
        "UsuarioCadastroId" integer NOT NULL,
        CONSTRAINT "PK_Obitos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Obitos_Capelas_CapelaId" FOREIGN KEY ("CapelaId") REFERENCES "Capelas" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Obitos_Usuarios_UsuarioCadastroId" FOREIGN KEY ("UsuarioCadastroId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE TABLE "Exumacoes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ObitoId" integer NOT NULL,
        "DataSolicitacao" timestamp with time zone NOT NULL,
        "DataPrevista" timestamp with time zone NOT NULL,
        "DataRealizacao" timestamp with time zone,
        "Status" character varying(50) NOT NULL,
        "LocalDestino" text NOT NULL,
        "Observacoes" text NOT NULL,
        "UsuarioResponsavelId" integer NOT NULL,
        CONSTRAINT "PK_Exumacoes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Exumacoes_Obitos_ObitoId" FOREIGN KEY ("ObitoId") REFERENCES "Obitos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Exumacoes_Usuarios_UsuarioResponsavelId" FOREIGN KEY ("UsuarioResponsavelId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE INDEX "IX_Exumacoes_ObitoId" ON "Exumacoes" ("ObitoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE INDEX "IX_Exumacoes_UsuarioResponsavelId" ON "Exumacoes" ("UsuarioResponsavelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE INDEX "IX_Obitos_CapelaId" ON "Obitos" ("CapelaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    CREATE INDEX "IX_Obitos_UsuarioCadastroId" ON "Obitos" ("UsuarioCadastroId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502195525_Inicial_Tabelas_Mortuario') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260502195525_Inicial_Tabelas_Mortuario', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    DROP TABLE "Exumacoes";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    DROP TABLE "Obitos";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "Nome" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "Email" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    ALTER TABLE "Capelas" ALTER COLUMN "Status" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    ALTER TABLE "Capelas" ALTER COLUMN "Nome" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "ConfiguracoesFinanceiras" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ValorMetroQuadrado" numeric(10,2) NOT NULL,
        "TaxaManutencaoBase" numeric(10,2) NOT NULL,
        "TaxaConcessaoBase" numeric(10,2) NOT NULL,
        "DataUltimaAtualizacao" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ConfiguracoesFinanceiras" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "Falecidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CausaDaMorte" text NOT NULL,
        CONSTRAINT "PK_Falecidos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "GavetasPublicas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Setor" text NOT NULL,
        "Quadra" text NOT NULL,
        "Lote" text NOT NULL,
        "NumeroGaveta" text NOT NULL,
        "Ocupada" boolean NOT NULL,
        "FalecidoId" integer,
        "DataOcupacao" timestamp with time zone,
        "DataPrevisaoExumacao" timestamp with time zone,
        CONSTRAINT "PK_GavetasPublicas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "ModelosJazigos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "PercentualConcessao" numeric(5,2) NOT NULL,
        "PercentualManutencao" numeric(5,2) NOT NULL,
        "TaxaConstrucao" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_ModelosJazigos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "RegistrosCapela" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CapelaId" integer NOT NULL,
        "AtendimentoId" integer NOT NULL,
        "HoraEntrada" timestamp with time zone NOT NULL,
        "HoraSaida" timestamp with time zone,
        CONSTRAINT "PK_RegistrosCapela" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "Responsaveis" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "CPF" text NOT NULL,
        "RG" text NOT NULL,
        "OrgaoEmissor" text NOT NULL,
        "Profissao" text NOT NULL,
        "Endereco" text NOT NULL,
        "Telefone" text NOT NULL,
        CONSTRAINT "PK_Responsaveis" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "Jazigos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CodigoIdentificador" text NOT NULL,
        "ModeloJazigoId" integer NOT NULL,
        "IsInfantil" boolean NOT NULL,
        "Ocupado" boolean NOT NULL,
        "JazigoPaiId" integer,
        "CoordenadasMapa" text NOT NULL,
        CONSTRAINT "PK_Jazigos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Jazigos_Jazigos_JazigoPaiId" FOREIGN KEY ("JazigoPaiId") REFERENCES "Jazigos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Jazigos_ModelosJazigos_ModeloJazigoId" FOREIGN KEY ("ModeloJazigoId") REFERENCES "ModelosJazigos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "Atendimentos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ResponsavelId" integer NOT NULL,
        "FalecidoId" integer NOT NULL,
        "Perfil" text NOT NULL,
        "Origem" text NOT NULL,
        "Procedimento" text NOT NULL,
        "NumeroOsAuxilio" text NOT NULL,
        "NumeroDeclaracaoObito" text NOT NULL,
        "LocalFalecimento" text NOT NULL,
        "LocalSepultamento" text NOT NULL,
        "DataSepultamento" timestamp with time zone,
        "HorarioSepultamento" interval,
        "PecaAnatomicaIdentificacao" text,
        "PecaAnatomicaDataCirurgia" timestamp with time zone,
        "PecaAnatomicaHospital" text,
        "PecaAnatomicaCidadeOrigem" text,
        "PecaAnatomicaEstadoOrigem" text,
        CONSTRAINT "PK_Atendimentos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Atendimentos_Falecidos_FalecidoId" FOREIGN KEY ("FalecidoId") REFERENCES "Falecidos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Atendimentos_Responsaveis_ResponsavelId" FOREIGN KEY ("ResponsavelId") REFERENCES "Responsaveis" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "ExumacoesRegistros" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FalecidoId" integer NOT NULL,
        "GavetaPublicaId" integer,
        "JazigoId" integer,
        "DataAutorizacao" timestamp with time zone NOT NULL,
        "SetorAutorizador" text NOT NULL,
        "DataExecucao" timestamp with time zone,
        "Executor" text NOT NULL,
        "Observacoes" text NOT NULL,
        CONSTRAINT "PK_ExumacoesRegistros" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExumacoesRegistros_Falecidos_FalecidoId" FOREIGN KEY ("FalecidoId") REFERENCES "Falecidos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ExumacoesRegistros_GavetasPublicas_GavetaPublicaId" FOREIGN KEY ("GavetaPublicaId") REFERENCES "GavetasPublicas" ("Id"),
        CONSTRAINT "FK_ExumacoesRegistros_Jazigos_JazigoId" FOREIGN KEY ("JazigoId") REFERENCES "Jazigos" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE TABLE "ItensFaturados" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AtendimentoId" integer NOT NULL,
        "CategoriaItem" text NOT NULL,
        "QuantidadeOuKm" numeric(10,2) NOT NULL,
        "ValorTotalCalculado" numeric(10,2) NOT NULL,
        "AbatidoDoEstoque" boolean NOT NULL,
        CONSTRAINT "PK_ItensFaturados" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ItensFaturados_Atendimentos_AtendimentoId" FOREIGN KEY ("AtendimentoId") REFERENCES "Atendimentos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_Atendimentos_FalecidoId" ON "Atendimentos" ("FalecidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_Atendimentos_ResponsavelId" ON "Atendimentos" ("ResponsavelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_ExumacoesRegistros_FalecidoId" ON "ExumacoesRegistros" ("FalecidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_ExumacoesRegistros_GavetaPublicaId" ON "ExumacoesRegistros" ("GavetaPublicaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_ExumacoesRegistros_JazigoId" ON "ExumacoesRegistros" ("JazigoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_GavetasPublicas_Ocupada" ON "GavetasPublicas" ("Ocupada");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE UNIQUE INDEX "IX_GavetasPublicas_Setor_Quadra_Lote_NumeroGaveta" ON "GavetasPublicas" ("Setor", "Quadra", "Lote", "NumeroGaveta");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_ItensFaturados_AtendimentoId" ON "ItensFaturados" ("AtendimentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_Jazigos_JazigoPaiId" ON "Jazigos" ("JazigoPaiId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    CREATE INDEX "IX_Jazigos_ModeloJazigoId" ON "Jazigos" ("ModeloJazigoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504152026_NovasRegras_Jazigos_Financas') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260504152026_NovasRegras_Jazigos_Financas', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" RENAME COLUMN "CausaDaMorte" TO "Nome";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" ADD "CausaMorte" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" ADD "Cpf" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" ADD "DataFalecimento" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" ADD "JazigoId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    CREATE INDEX "IX_Falecidos_JazigoId" ON "Falecidos" ("JazigoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    ALTER TABLE "Falecidos" ADD CONSTRAINT "FK_Falecidos_Jazigos_JazigoId" FOREIGN KEY ("JazigoId") REFERENCES "Jazigos" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513220456_AjustandoCausaMorteEnum') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260513220456_AjustandoCausaMorteEnum', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Usuarios" ALTER COLUMN "Nome" TYPE character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "Telefone" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "RG" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "Profissao" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "OrgaoEmissor" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "Nome" TYPE character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Responsaveis" ALTER COLUMN "Endereco" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ModelosJazigos" ALTER COLUMN "Nome" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Jazigos" ALTER COLUMN "CoordenadasMapa" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Jazigos" ALTER COLUMN "CodigoIdentificador" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ItensFaturados" ALTER COLUMN "CategoriaItem" TYPE character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "GavetasPublicas" ALTER COLUMN "Setor" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "GavetasPublicas" ALTER COLUMN "Quadra" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "GavetasPublicas" ALTER COLUMN "NumeroGaveta" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "GavetasPublicas" ALTER COLUMN "Lote" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Falecidos" ALTER COLUMN "Nome" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ExumacoesRegistros" ALTER COLUMN "SetorAutorizador" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ExumacoesRegistros" ALTER COLUMN "Observacoes" TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "AtualizadoPor" character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "PrecoPompa" numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "PrecoPreparoCorpo" numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "PrecoTransladoPorKm" numeric(10,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "PrecoUrnaBasica" numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "ConfiguracoesFinanceiras" ADD "PrecoUrnaEspecial" numeric(10,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Capelas" ALTER COLUMN "Status" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Capelas" ALTER COLUMN "Nome" TYPE character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Capelas" ALTER COLUMN "Localizacao" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "PecaAnatomicaIdentificacao" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "PecaAnatomicaHospital" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "PecaAnatomicaEstadoOrigem" TYPE character varying(2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "PecaAnatomicaCidadeOrigem" TYPE character varying(150);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "NumeroOsAuxilio" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "NumeroDeclaracaoObito" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "LocalSepultamento" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "Atendimentos" ALTER COLUMN "LocalFalecimento" TYPE character varying(250);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    CREATE INDEX "IX_RegistrosCapela_AtendimentoId" ON "RegistrosCapela" ("AtendimentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    CREATE INDEX "IX_RegistrosCapela_CapelaId" ON "RegistrosCapela" ("CapelaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    CREATE INDEX "IX_GavetasPublicas_FalecidoId" ON "GavetasPublicas" ("FalecidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "GavetasPublicas" ADD CONSTRAINT "FK_GavetasPublicas_Falecidos_FalecidoId" FOREIGN KEY ("FalecidoId") REFERENCES "Falecidos" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "RegistrosCapela" ADD CONSTRAINT "FK_RegistrosCapela_Atendimentos_AtendimentoId" FOREIGN KEY ("AtendimentoId") REFERENCES "Atendimentos" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    ALTER TABLE "RegistrosCapela" ADD CONSTRAINT "FK_RegistrosCapela_Capelas_CapelaId" FOREIGN KEY ("CapelaId") REFERENCES "Capelas" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514022242_ConfiguracaoFinanceira_TabelaPrecos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260514022242_ConfiguracaoFinanceira_TabelaPrecos', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514183016_Add_Falecidos_Collection_To_Jazigo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260514183016_Add_Falecidos_Collection_To_Jazigo', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514194647_AjusteExumacaoEPeçaAnatomica') THEN
    ALTER TABLE "Falecidos" DROP CONSTRAINT "FK_Falecidos_Jazigos_JazigoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514194647_AjusteExumacaoEPeçaAnatomica') THEN
    ALTER TABLE "Falecidos" ALTER COLUMN "JazigoId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514194647_AjusteExumacaoEPeçaAnatomica') THEN
    ALTER TABLE "Falecidos" ADD "IsPecaAnatomica" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514194647_AjusteExumacaoEPeçaAnatomica') THEN
    ALTER TABLE "Falecidos" ADD CONSTRAINT "FK_Falecidos_Jazigos_JazigoId" FOREIGN KEY ("JazigoId") REFERENCES "Jazigos" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514194647_AjusteExumacaoEPeçaAnatomica') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260514194647_AjusteExumacaoEPeçaAnatomica', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Falecidos" DROP COLUMN "IsPecaAnatomica";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Falecidos" ADD "OssuarioId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Falecidos" ADD "TipoRestosMortais" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "ExumacoesRegistros" ADD "OssuarioDestinoId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Atendimentos" ADD "FunerariaId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE TABLE "Funerarias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "CNPJ" character varying(20) NOT NULL,
        "Telefone" character varying(20) NOT NULL,
        "Endereco" character varying(250) NOT NULL,
        CONSTRAINT "PK_Funerarias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE TABLE "HistoricoTitularidadeJazigos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JazigoId" integer NOT NULL,
        "ResponsavelAntigoId" integer NOT NULL,
        "ResponsavelNovoId" integer NOT NULL,
        "DataTransferencia" timestamp with time zone NOT NULL,
        "Motivo" character varying(500) NOT NULL,
        "UsuarioId" integer,
        CONSTRAINT "PK_HistoricoTitularidadeJazigos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HistoricoTitularidadeJazigos_Jazigos_JazigoId" FOREIGN KEY ("JazigoId") REFERENCES "Jazigos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_HistoricoTitularidadeJazigos_Responsaveis_ResponsavelAntigo~" FOREIGN KEY ("ResponsavelAntigoId") REFERENCES "Responsaveis" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_HistoricoTitularidadeJazigos_Responsaveis_ResponsavelNovoId" FOREIGN KEY ("ResponsavelNovoId") REFERENCES "Responsaveis" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_HistoricoTitularidadeJazigos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE TABLE "Ossuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Identificador" character varying(100) NOT NULL,
        "Tipo" text NOT NULL,
        "JazigoVinculadoId" integer,
        "Capacidade" integer NOT NULL,
        "Ocupado" boolean NOT NULL,
        CONSTRAINT "PK_Ossuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ossuarios_Jazigos_JazigoVinculadoId" FOREIGN KEY ("JazigoVinculadoId") REFERENCES "Jazigos" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE TABLE "ProdutosEstoque" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(150) NOT NULL,
        "QuantidadeDisponivel" integer NOT NULL,
        "EstoqueMinimo" integer NOT NULL,
        "Custo" numeric(10,2) NOT NULL,
        "ValorVenda" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_ProdutosEstoque" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE TABLE "MovimentacoesEstoque" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProdutoEstoqueId" integer NOT NULL,
        "TipoMovimentacao" text NOT NULL,
        "Quantidade" integer NOT NULL,
        "DataMovimentacao" timestamp with time zone NOT NULL,
        "Motivo" character varying(250) NOT NULL,
        CONSTRAINT "PK_MovimentacoesEstoque" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MovimentacoesEstoque_ProdutosEstoque_ProdutoEstoqueId" FOREIGN KEY ("ProdutoEstoqueId") REFERENCES "ProdutosEstoque" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_Falecidos_OssuarioId" ON "Falecidos" ("OssuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_ExumacoesRegistros_OssuarioDestinoId" ON "ExumacoesRegistros" ("OssuarioDestinoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_Atendimentos_FunerariaId" ON "Atendimentos" ("FunerariaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_HistoricoTitularidadeJazigos_JazigoId" ON "HistoricoTitularidadeJazigos" ("JazigoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_HistoricoTitularidadeJazigos_ResponsavelAntigoId" ON "HistoricoTitularidadeJazigos" ("ResponsavelAntigoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_HistoricoTitularidadeJazigos_ResponsavelNovoId" ON "HistoricoTitularidadeJazigos" ("ResponsavelNovoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_HistoricoTitularidadeJazigos_UsuarioId" ON "HistoricoTitularidadeJazigos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_MovimentacoesEstoque_ProdutoEstoqueId" ON "MovimentacoesEstoque" ("ProdutoEstoqueId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    CREATE INDEX "IX_Ossuarios_JazigoVinculadoId" ON "Ossuarios" ("JazigoVinculadoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Atendimentos" ADD CONSTRAINT "FK_Atendimentos_Funerarias_FunerariaId" FOREIGN KEY ("FunerariaId") REFERENCES "Funerarias" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "ExumacoesRegistros" ADD CONSTRAINT "FK_ExumacoesRegistros_Ossuarios_OssuarioDestinoId" FOREIGN KEY ("OssuarioDestinoId") REFERENCES "Ossuarios" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    ALTER TABLE "Falecidos" ADD CONSTRAINT "FK_Falecidos_Ossuarios_OssuarioId" FOREIGN KEY ("OssuarioId") REFERENCES "Ossuarios" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515014829_LegacyFeaturesImport') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515014829_LegacyFeaturesImport', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515164834_AddOperationalFeatures') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515164834_AddOperationalFeatures', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526020334_AddLockoutFields') THEN
    ALTER TABLE "Usuarios" ADD "BloqueadoAte" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526020334_AddLockoutFields') THEN
    ALTER TABLE "Usuarios" ADD "TentativasLoginFalhas" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526020334_AddLockoutFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260526020334_AddLockoutFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526021344_AddAuditLog') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "NomeUsuario" character varying(150) NOT NULL,
        "Acao" character varying(50) NOT NULL,
        "NomeEntidade" character varying(100) NOT NULL,
        "EntidadeId" character varying(100) NOT NULL,
        "DataHoraUtc" timestamp with time zone NOT NULL,
        "ValoresAntigos" text,
        "ValoresNovos" text,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526021344_AddAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260526021344_AddAuditLog', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    ALTER TABLE "Ossuarios" DROP COLUMN "Ocupado";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    ALTER TABLE "Falecidos" ADD "Status" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    CREATE TABLE "DocumentosAnexos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AtendimentoId" integer NOT NULL,
        "FalecidoId" integer NOT NULL,
        "NomeArquivo" character varying(260) NOT NULL,
        "CaminhoArquivo" character varying(512) NOT NULL,
        "TamanhoBytes" bigint NOT NULL,
        "DataAnexo" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DocumentosAnexos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DocumentosAnexos_Atendimentos_AtendimentoId" FOREIGN KEY ("AtendimentoId") REFERENCES "Atendimentos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_DocumentosAnexos_Falecidos_FalecidoId" FOREIGN KEY ("FalecidoId") REFERENCES "Falecidos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    CREATE INDEX "IX_Atendimentos_DataSepultamento" ON "Atendimentos" ("DataSepultamento");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    CREATE INDEX "IX_DocumentosAnexos_AtendimentoId" ON "DocumentosAnexos" ("AtendimentoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    CREATE INDEX "IX_DocumentosAnexos_FalecidoId" ON "DocumentosAnexos" ("FalecidoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629212908_AddStatusFalecidoEDocumentosAnexos') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629212908_AddStatusFalecidoEDocumentosAnexos', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Ossuarios" ADD "Ala" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Ossuarios" ADD "NumeroLote" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Ossuarios" ADD "Quadra" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Jazigos" ADD "Ala" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Jazigos" ADD "NumeroLote" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    ALTER TABLE "Jazigos" ADD "Quadra" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629230553_AddMapFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629230553_AddMapFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706135245_AddOsFinalizadaToAtendimento') THEN
    ALTER TABLE "Atendimentos" ADD "OsFinalizada" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706135245_AddOsFinalizadaToAtendimento') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260706135245_AddOsFinalizadaToAtendimento', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706142744_AddHorarioExecucaoToExumacao') THEN
    ALTER TABLE "ExumacoesRegistros" ADD "HorarioExecucao" interval;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260706142744_AddHorarioExecucaoToExumacao') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260706142744_AddHorarioExecucaoToExumacao', '8.0.0');
    END IF;
END $EF$;
COMMIT;

