// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sakrus.Infrastructure.Data;

#nullable disable

namespace Sakrus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001002359_AmpliarCodigoTipoDocumento")]
    partial class AmpliarCodigoTipoDocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sakrus.Core.Entities.AssuntoProtocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("GeraRegularizacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("AssuntosProtocolo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AssuntoProtocoloDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssuntoProtocoloId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDocumentoCodigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoProtocoloId", "TipoDocumentoCodigo")
                        .IsUnique();

                    b.ToTable("AssuntosProtocoloDocumentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataSepultamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmpresaExecutoraId")
                        .HasColumnType("integer");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("FunerariaId")
                        .HasColumnType("integer");

                    b.Property<string>("GrauParentesco")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<TimeSpan?>("HorarioSepultamento")
                        .HasColumnType("interval");

                    b.Property<bool?>("LiberacaoMunicipal")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalFalecimento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LocalSepultamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NumeroDeclaracaoObito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroOsAuxilio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OsFinalizada")
                        .HasColumnType("boolean");

                    b.Property<string>("PecaAnatomicaCidadeOrigem")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("PecaAnatomicaDataCirurgia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PecaAnatomicaEstadoOrigem")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("PecaAnatomicaHospital")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PecaAnatomicaIdentificacao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSepultamento");

                    b.HasIndex("EmpresaExecutoraId");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("FunerariaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AtendimentoServicoAuxilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicoAuxilioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicoAuxilioId");

                    b.HasIndex("AtendimentoId", "ServicoAuxilioId")
                        .IsUnique();

                    b.ToTable("AtendimentosServicosAuxilio");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataHoraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Capela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Capelas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Cemiterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Cemiterios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ClassificacaoEspaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ClassificacoesEspaco");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ConfiguracaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecoPompa")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoPreparoCorpo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoTransladoPorKm")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PrecoUrnaBasica")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoUrnaEspecial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TaxaConcessaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TaxaManutencaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorMetroQuadrado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesFinanceiras");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ConfiguracaoInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CabecalhoLinha1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CabecalhoLinha2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CargoCoordenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MunicipioEmissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeCoordenador")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomePresidenteConselho")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UfEmissao")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesInstitucionais");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.DocumentoAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("DataAnexo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("FunerariaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("FunerariaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("DocumentosAnexos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.DocumentoEmitido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DadosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EmitidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmitidoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("EmitidoPorNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PdfCaminho")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.Property<int>("Versao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId", "EntidadeTipo", "EntidadeId");

                    b.ToTable("DocumentosEmitidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAutorizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("GavetaPublicaId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HorarioExecucao")
                        .HasColumnType("interval");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OssuarioDestinoId")
                        .HasColumnType("integer");

                    b.Property<string>("SetorAutorizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("GavetaPublicaId");

                    b.HasIndex("JazigoId");

                    b.HasIndex("OssuarioDestinoId");

                    b.ToTable("ExumacoesRegistros");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CartorioRegistro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CausaMorte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoIndigente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataFalecimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSepultamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhIndigente")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("LocalCorpo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MatriculaObito")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MunicipioCartorio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomePai")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("OssuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRestosMortais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JazigoId");

                    b.HasIndex("OssuarioId");

                    b.ToTable("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Funeraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EhExecutora")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Funerarias");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Gaveta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassificacaoEspacoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataSepultamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificacaoEspacoId");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("JazigoId", "Numero")
                        .IsUnique();

                    b.ToTable("Gavetas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.GavetaPublica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CemiterioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassificacaoEspacoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataOcupacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevisaoExumacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInfantil")
                        .HasColumnType("boolean");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroGaveta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CemiterioId");

                    b.HasIndex("ClassificacaoEspacoId");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("Ocupada");

                    b.HasIndex("Setor", "Quadra", "Lote", "NumeroGaveta")
                        .IsUnique();

                    b.ToTable("GavetasPublicas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.HistoricoTitularidadeJazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResponsavelAntigoId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsavelNovoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JazigoId");

                    b.HasIndex("ResponsavelAntigoId");

                    b.HasIndex("ResponsavelNovoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoTitularidadeJazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbatidoDoEstoque")
                        .HasColumnType("boolean");

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("QuantidadeOuKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorTotalCalculado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("ItensFaturados");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CemiterioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassificacaoEspacoId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Comprimento")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CoordenadasMapa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsInfantil")
                        .HasColumnType("boolean");

                    b.Property<int?>("JazigoPaiId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Largura")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ModeloJazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Revestimento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CemiterioId");

                    b.HasIndex("ClassificacaoEspacoId");

                    b.HasIndex("JazigoPaiId");

                    b.HasIndex("ModeloJazigoId");

                    b.ToTable("Jazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.JazigoProprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HerdeiroPrevistId")
                        .HasColumnType("integer");

                    b.Property<int>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PagamentoConfirmado")
                        .HasColumnType("boolean");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoVinculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HerdeiroPrevistId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("JazigoId", "Ativo");

                    b.HasIndex("ResponsavelId", "Ativo");

                    b.ToTable("JazigoProprietarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer");

                    b.Property<int>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("JazigoId");

                    b.ToTable("LancamentosFinanceiros");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ModeloJazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PercentualConcessao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PercentualManutencao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TaxaConstrucao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ModelosJazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ProdutoEstoqueId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoEstoqueId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.NumeroRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Chave", "Ano", "Sequencia")
                        .IsUnique();

                    b.HasIndex("Chave", "EntidadeTipo", "EntidadeId")
                        .IsUnique();

                    b.ToTable("NumerosRegistro");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("JazigoVinculadoId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JazigoVinculadoId");

                    b.ToTable("Ossuarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ProdutoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Custo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ProdutosEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Protocolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("AssuntoProtocoloId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoProtocoloId");

                    b.HasIndex("JazigoId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("Ano", "Sequencia")
                        .IsUnique();

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.RegistroCapela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("CapelaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CapelaId");

                    b.ToTable("RegistrosCapela");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EhProprietario")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ServicoAuxilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ServicosAuxilio");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveNumeracao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("ExigeNumeroUnico")
                        .HasColumnType("boolean");

                    b.Property<bool>("GeraNumeroNaPrimeiraEmissao")
                        .HasColumnType("boolean");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TentativasLoginFalhas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ValorMetroQuadrado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Exercicio")
                        .IsUnique();

                    b.ToTable("ValoresMetroQuadrado");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AssuntoProtocoloDocumento", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.AssuntoProtocolo", "AssuntoProtocolo")
                        .WithMany("Documentos")
                        .HasForeignKey("AssuntoProtocoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssuntoProtocolo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Funeraria", "EmpresaExecutora")
                        .WithMany()
                        .HasForeignKey("EmpresaExecutoraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Funeraria", "Funeraria")
                        .WithMany("Atendimentos")
                        .HasForeignKey("FunerariaId");

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpresaExecutora");

                    b.Navigation("Falecido");

                    b.Navigation("Funeraria");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AtendimentoServicoAuxilio", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("ServicosAuxilio")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.ServicoAuxilio", "ServicoAuxilio")
                        .WithMany()
                        .HasForeignKey("ServicoAuxilioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("ServicoAuxilio");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.DocumentoAnexo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany("Documentos")
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sakrus.Core.Entities.Funeraria", "Funeraria")
                        .WithMany("Documentos")
                        .HasForeignKey("FunerariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany("Documentos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Atendimento");

                    b.Navigation("Falecido");

                    b.Navigation("Funeraria");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.DocumentoEmitido", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.GavetaPublica", "GavetaPublica")
                        .WithMany()
                        .HasForeignKey("GavetaPublicaId");

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId");

                    b.HasOne("Sakrus.Core.Entities.Ossuario", "OssuarioDestino")
                        .WithMany()
                        .HasForeignKey("OssuarioDestinoId");

                    b.Navigation("Falecido");

                    b.Navigation("GavetaPublica");

                    b.Navigation("Jazigo");

                    b.Navigation("OssuarioDestino");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany("Falecidos")
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakrus.Core.Entities.Ossuario", "Ossuario")
                        .WithMany("Falecidos")
                        .HasForeignKey("OssuarioId");

                    b.Navigation("Jazigo");

                    b.Navigation("Ossuario");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Gaveta", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.ClassificacaoEspaco", "ClassificacaoEspaco")
                        .WithMany()
                        .HasForeignKey("ClassificacaoEspacoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany("Gavetas")
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassificacaoEspaco");

                    b.Navigation("Falecido");

                    b.Navigation("Jazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.GavetaPublica", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Cemiterio", "Cemiterio")
                        .WithMany()
                        .HasForeignKey("CemiterioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.ClassificacaoEspaco", "ClassificacaoEspaco")
                        .WithMany()
                        .HasForeignKey("ClassificacaoEspacoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId");

                    b.Navigation("Cemiterio");

                    b.Navigation("ClassificacaoEspaco");

                    b.Navigation("Falecido");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.HistoricoTitularidadeJazigo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "ResponsavelAntigo")
                        .WithMany()
                        .HasForeignKey("ResponsavelAntigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "ResponsavelNovo")
                        .WithMany()
                        .HasForeignKey("ResponsavelNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Jazigo");

                    b.Navigation("ResponsavelAntigo");

                    b.Navigation("ResponsavelNovo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("ItensFaturados")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Cemiterio", "Cemiterio")
                        .WithMany()
                        .HasForeignKey("CemiterioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.ClassificacaoEspaco", "ClassificacaoEspaco")
                        .WithMany()
                        .HasForeignKey("ClassificacaoEspacoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "JazigoPai")
                        .WithMany()
                        .HasForeignKey("JazigoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.ModeloJazigo", "ModeloJazigo")
                        .WithMany()
                        .HasForeignKey("ModeloJazigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cemiterio");

                    b.Navigation("ClassificacaoEspaco");

                    b.Navigation("JazigoPai");

                    b.Navigation("ModeloJazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.JazigoProprietario", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Responsavel", "HerdeiroPrevisto")
                        .WithMany()
                        .HasForeignKey("HerdeiroPrevistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany("Proprietarios")
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany("JazigoProprietarios")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("HerdeiroPrevisto");

                    b.Navigation("Jazigo");

                    b.Navigation("Responsavel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.LancamentoFinanceiro", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.ProdutoEstoque", "ProdutoEstoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "JazigoVinculado")
                        .WithMany()
                        .HasForeignKey("JazigoVinculadoId");

                    b.Navigation("JazigoVinculado");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Protocolo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.AssuntoProtocolo", "AssuntoProtocolo")
                        .WithMany()
                        .HasForeignKey("AssuntoProtocoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssuntoProtocolo");

                    b.Navigation("Jazigo");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.RegistroCapela", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Capela", "Capela")
                        .WithMany()
                        .HasForeignKey("CapelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Capela");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.AssuntoProtocolo", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Navigation("ItensFaturados");

                    b.Navigation("ServicosAuxilio");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Funeraria", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.Navigation("Falecidos");

                    b.Navigation("Gavetas");

                    b.Navigation("Proprietarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.Navigation("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ProdutoEstoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Responsavel", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("JazigoProprietarios");
                });
#pragma warning restore 612, 618
        }
    }
}
