// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sakrus.Infrastructure.Data;

#nullable disable

namespace Sakrus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515164834_AddOperationalFeatures")]
    partial class AddOperationalFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataSepultamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("FunerariaId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HorarioSepultamento")
                        .HasColumnType("interval");

                    b.Property<string>("LocalFalecimento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LocalSepultamento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("NumeroDeclaracaoObito")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroOsAuxilio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PecaAnatomicaCidadeOrigem")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("PecaAnatomicaDataCirurgia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PecaAnatomicaEstadoOrigem")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("PecaAnatomicaHospital")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PecaAnatomicaIdentificacao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("FunerariaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Capela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Capelas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ConfiguracaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtualizadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecoPompa")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoPreparoCorpo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoTransladoPorKm")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PrecoUrnaBasica")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PrecoUrnaEspecial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TaxaConcessaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TaxaManutencaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorMetroQuadrado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesFinanceiras");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAutorizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("GavetaPublicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OssuarioDestinoId")
                        .HasColumnType("integer");

                    b.Property<string>("SetorAutorizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("GavetaPublicaId");

                    b.HasIndex("JazigoId");

                    b.HasIndex("OssuarioDestinoId");

                    b.ToTable("ExumacoesRegistros");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CausaMorte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataFalecimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OssuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoRestosMortais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JazigoId");

                    b.HasIndex("OssuarioId");

                    b.ToTable("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Funeraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Funerarias");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.GavetaPublica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataOcupacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevisaoExumacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroGaveta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("Ocupada");

                    b.HasIndex("Setor", "Quadra", "Lote", "NumeroGaveta")
                        .IsUnique();

                    b.ToTable("GavetasPublicas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.HistoricoTitularidadeJazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResponsavelAntigoId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsavelNovoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JazigoId");

                    b.HasIndex("ResponsavelAntigoId");

                    b.HasIndex("ResponsavelNovoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoTitularidadeJazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbatidoDoEstoque")
                        .HasColumnType("boolean");

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("QuantidadeOuKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorTotalCalculado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("ItensFaturados");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdentificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoordenadasMapa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsInfantil")
                        .HasColumnType("boolean");

                    b.Property<int?>("JazigoPaiId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeloJazigoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("JazigoPaiId");

                    b.HasIndex("ModeloJazigoId");

                    b.ToTable("Jazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ModeloJazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PercentualConcessao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PercentualManutencao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TaxaConstrucao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ModelosJazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("ProdutoEstoqueId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoEstoqueId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("JazigoVinculadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JazigoVinculadoId");

                    b.ToTable("Ossuarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ProdutoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Custo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ProdutosEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.RegistroCapela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("CapelaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CapelaId");

                    b.ToTable("RegistrosCapela");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Funeraria", "Funeraria")
                        .WithMany("Atendimentos")
                        .HasForeignKey("FunerariaId");

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Falecido");

                    b.Navigation("Funeraria");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.GavetaPublica", "GavetaPublica")
                        .WithMany()
                        .HasForeignKey("GavetaPublicaId");

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId");

                    b.HasOne("Sakrus.Core.Entities.Ossuario", "OssuarioDestino")
                        .WithMany()
                        .HasForeignKey("OssuarioDestinoId");

                    b.Navigation("Falecido");

                    b.Navigation("GavetaPublica");

                    b.Navigation("Jazigo");

                    b.Navigation("OssuarioDestino");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany("Falecidos")
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sakrus.Core.Entities.Ossuario", "Ossuario")
                        .WithMany("Falecidos")
                        .HasForeignKey("OssuarioId");

                    b.Navigation("Jazigo");

                    b.Navigation("Ossuario");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.GavetaPublica", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId");

                    b.Navigation("Falecido");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.HistoricoTitularidadeJazigo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "ResponsavelAntigo")
                        .WithMany()
                        .HasForeignKey("ResponsavelAntigoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "ResponsavelNovo")
                        .WithMany()
                        .HasForeignKey("ResponsavelNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Jazigo");

                    b.Navigation("ResponsavelAntigo");

                    b.Navigation("ResponsavelNovo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("ItensFaturados")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "JazigoPai")
                        .WithMany()
                        .HasForeignKey("JazigoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.ModeloJazigo", "ModeloJazigo")
                        .WithMany()
                        .HasForeignKey("ModeloJazigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JazigoPai");

                    b.Navigation("ModeloJazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.ProdutoEstoque", "ProdutoEstoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoEstoque");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "JazigoVinculado")
                        .WithMany()
                        .HasForeignKey("JazigoVinculadoId");

                    b.Navigation("JazigoVinculado");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.RegistroCapela", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Capela", "Capela")
                        .WithMany()
                        .HasForeignKey("CapelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Capela");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Navigation("ItensFaturados");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Funeraria", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.Navigation("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Ossuario", b =>
                {
                    b.Navigation("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ProdutoEstoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
