// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sakrus.Infrastructure.Data;

#nullable disable

namespace Sakrus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataSepultamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HorarioSepultamento")
                        .HasColumnType("interval");

                    b.Property<string>("LocalFalecimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalSepultamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDeclaracaoObito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroOsAuxilio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PecaAnatomicaCidadeOrigem")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PecaAnatomicaDataCirurgia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PecaAnatomicaEstadoOrigem")
                        .HasColumnType("text");

                    b.Property<string>("PecaAnatomicaHospital")
                        .HasColumnType("text");

                    b.Property<string>("PecaAnatomicaIdentificacao")
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Procedimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Capela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Capelas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ConfiguracaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TaxaConcessaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TaxaManutencaoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorMetroQuadrado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesFinanceiras");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAutorizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("GavetaPublicaId")
                        .HasColumnType("integer");

                    b.Property<int?>("JazigoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorAutorizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FalecidoId");

                    b.HasIndex("GavetaPublicaId");

                    b.HasIndex("JazigoId");

                    b.ToTable("ExumacoesRegistros");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Falecido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CausaDaMorte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Falecidos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.GavetaPublica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataOcupacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevisaoExumacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FalecidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroGaveta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean");

                    b.Property<string>("Quadra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ocupada");

                    b.HasIndex("Setor", "Quadra", "Lote", "NumeroGaveta")
                        .IsUnique();

                    b.ToTable("GavetasPublicas");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AbatidoDoEstoque")
                        .HasColumnType("boolean");

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriaItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantidadeOuKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorTotalCalculado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("ItensFaturados");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdentificador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoordenadasMapa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInfantil")
                        .HasColumnType("boolean");

                    b.Property<int?>("JazigoPaiId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeloJazigoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("JazigoPaiId");

                    b.HasIndex("ModeloJazigoId");

                    b.ToTable("Jazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ModeloJazigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PercentualConcessao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PercentualManutencao")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TaxaConstrucao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ModelosJazigos");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.RegistroCapela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("CapelaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RegistrosCapela");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Falecido");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ExumacaoRegistro", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Falecido", "Falecido")
                        .WithMany()
                        .HasForeignKey("FalecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sakrus.Core.Entities.GavetaPublica", "GavetaPublica")
                        .WithMany()
                        .HasForeignKey("GavetaPublicaId");

                    b.HasOne("Sakrus.Core.Entities.Jazigo", "Jazigo")
                        .WithMany()
                        .HasForeignKey("JazigoId");

                    b.Navigation("Falecido");

                    b.Navigation("GavetaPublica");

                    b.Navigation("Jazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.ItemFaturado", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Atendimento", "Atendimento")
                        .WithMany("ItensFaturados")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Jazigo", b =>
                {
                    b.HasOne("Sakrus.Core.Entities.Jazigo", "JazigoPai")
                        .WithMany()
                        .HasForeignKey("JazigoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sakrus.Core.Entities.ModeloJazigo", "ModeloJazigo")
                        .WithMany()
                        .HasForeignKey("ModeloJazigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JazigoPai");

                    b.Navigation("ModeloJazigo");
                });

            modelBuilder.Entity("Sakrus.Core.Entities.Atendimento", b =>
                {
                    b.Navigation("ItensFaturados");
                });
#pragma warning restore 612, 618
        }
    }
}
